### ISSUE TITLE
Annotation @mixin in Arrays needs to be imported

### ISSUE THREAD

**Issue by stiggg** [Anahkiasen/underscore-php#18]
I get a following error when trying to use version 1.2.2: "[Semantical Error] The annotation "@mixin" in class Underscore\Types\Arrays was never imported. Did you maybe forget to add a "use" statement for this annotation?" 

It seems Arrays class needs a correct use statement?

**Comment by velosipedist** [comment]
i suppose, it is Symfony 2 annotations parser bug. AFAIK @mixin is documented standard PHPDoc tag, therrefore it is Symfony related bug.
