### ISSUE TITLE
Received error when installing with latest Laravel (5.0.27)

### ISSUE THREAD

**Issue by mikeerickson** [Anahkiasen/underscore-php#55]
Hey There

Finally decided to give this a whirl (use lodash all the time in JS land) and wanted to have similar routines while working on a couple PHP projects.

So, using 

"anahkiasen/underscore-php": "dev-master"

It produces a bunch of errors related to Laravel minimum version....

http://d.pr/i/18bEH

Any updated version working with L5 latest?

**Comment by mcordingley** [comment]
This is the same issue as #50.

**Comment by mikeerickson** [comment]
@mcordingley yes, indeed it is... If / when this gets updated, I will check back.

**Comment by Anahkiasen** [comment]
Closes by #56
