### ISSUE TITLE
Php 7 - Fatal error: Cannot use Underscore\Types\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by maarekj** [Anahkiasen/underscore-php#78]
In php7 there is this error:

    Fatal error: Cannot use Underscore\Types\String as String because 'String' is a special class name in /myproject/vendor/anahkiasen/underscore-php/src/Methods/StringMethods.php on line 5

Php7 not allows the classes to have a name like *string*, *bool*, *int*, ...
See http://php.net/manual/en/reserved.other-reserved-words.php for more details

**Comment by maarekj** [comment]
Sorry this bug has fixed in recent version of *underscore-php*

**Comment by itsazzad** [comment]
Not working with me

**Comment by jonathanbell** [comment]
+1

**Comment by maarekj** [comment]
@itsazzad @jonathanbell What is the issue and what is the version of the lib ?
