### ISSUE TITLE
multi-array to assoc based on key

### ISSUE THREAD

**Issue by scragg0x** [Anahkiasen/underscore-php#87]
Not sure if I can already efficiently do this with the current functions but I often used the following to convert a regular array of associative arrays to an associative array of same arrays by a given key (my example should make more sense).

I called it array hash map, probably not the best name though.

``` php
function array_hash_map($key, $array) {
        if (!$array) {
            return [];
        }
        $ret = [];
        foreach ($array as $a) {
            $ret[$a[$key]] = $a;
        }
        return $ret;
    }
```

Example:

``` php
$a = [
 ['id' => 5, 'name': foo],
 ['id' => 10, 'name': bar]
];

$a = array_hash_map('id', $a);

/*
  $a is now: 
  [
    '5' => ['id' => 5, 'name': foo],
    '10' => ['id' => 10, 'name': bar]
  ]
*/
```

Just a suggestion of a possible utility function for Arrays.

**Comment by scragg0x** [comment]
Actually this is the same as lodash indexBy

https://github.com/lodash/lodash/blob/3.10.1/doc/README.md#_indexbycollection-iteratee_identity-thisarg

**Comment by thesebas** [comment]
and same as Example #2 of http://php.net/manual/en/function.array-column.php

**Comment by scragg0x** [comment]
array_column($a, null, 'id');
